# Generated by Django 5.2.9 on 2026-01-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='logId',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sId',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selId',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='BabyProduct',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventBooking',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
