# Generated by Django 5.2.9 on 2026-01-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cartitem_product_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='baby_songs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('health', 'Health'), ('pregnancy', 'Pregnancy'), ('parenting', 'Parenting'), ('exercise', 'Exercise')], default='health', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tips/')),
                ('is_admin_authored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryTip',
        ),
        migrations.DeleteModel(
            name='HealingTip',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
